listener 1883
allow_anonymous false
password_file /etc/mosquitto/passwd

connection ttc_cloud_bridge
address <CLOUD_IP>:1883
topic ttc/fog/+/demand       out 1
topic ttc/fog/+/congestion   out 1
topic ttc/fog/+/advisory     out 1
topic ttc/fog/+/choke        out 1
topic ttc/edge/+/+/delay     out 1
topic ttc/edge/+/+/telemetry out 1
