listener 1883
allow_anonymous true 

connection ttc_cloud_bridge
address localhost:1886
topic ttc/fog/+/demand       out 1
topic ttc/fog/+/congestion   out 1
topic ttc/fog/+/advisory     out 1
topic ttc/fog/+/choke        out 1
topic ttc/edge/+/+/delay     out 1
topic ttc/edge/+/+/telemetry out 1
